Here-You/here-you-backend

src/app.controller.ts, src/app.service.ts, src/main.ts
Nest 기본 config를 설정한다.
<br><br>
<br><br>
<br><br>
- #24 
<br><br>
=> [Feat] Nest.js 기본 config 설정

.env.example, package-lock.json, package.json, src/utils/S3.module.ts, src/utils/S3.service.ts
S3에 이미지를 업로드하는 util class를 추가한다.
<br><br>
<br><br>
추후 Content-Type mime을 지정할 필요가 있어 보입니다.
<br><br>
- Close #27
<br><br>
=> [Feat] 이미지 업로드 Util 추가

.github/workflows/deploy-dev.yml
develop 브랜치에 merge 될 때마다 개발서버에 자동 배포한다.
<br><br>
<br><br>
SSH 접속 정보는 Secret으로 저장되어 있습니다.
<br><br>
- Close #32
<br><br>
=> [Chore] 개발서버 자동 배포 스크립트 추가

src/user/user.guard.ts, src/user/user.service.ts
토큰 발급이 정상적으로 되지 않아 로그인이 동작하지 않는 오류를 수정한다.
<br><br>
<br><br>
<br><br>
- Close #34 
<br><br>
=> [Fix] 로그인이 정상적으로 이루어지지 않는 오류 수정 

src/main.ts
프론트엔드 개발 환경을 위해 CORS를 활성화한다.
<br><br>
<br><br>
현재는 모든 origin에 대해 CORS가 활성화되어 있는데, 프로덕션에서는 프론트엔드 origin에 대해서만 활성화할 필요가 있다.
<br><br>
- #24 
<br><br>
=> [Chore] CORS 활성화

src/user/user.service.ts
이메일 로그인이 정상적으로 이루어지지 않는 오류를 수정
<br><br>
<br><br>
<br><br>
- Close #43
<br><br>
=> [Fix] 이메일 로그인이 정상적으로 작동하지 않는 문제를 수정

src/search/search.controller.ts, src/signature/domain/signature.entity.ts, src/signature/domain/signature.page.entity.ts, src/signature/dto/author-signature.dto.ts, src/signature/dto/tmp-userId.dto.ts, src/signature/signature.controller.ts, src/signature/signature.service.ts
[Refactor] 시그니처, 탐색 @UserGaurd 리팩토링
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [Refactor] 시그니처, 탐색 @UserGaurd 리팩토링 #56

src/user/user.controller.ts
닉네임 수정과 프로필 소개 수정 API를 추가하라
<br><br>
<br><br>
기 개발된 서비스 코드를 재사용 할 수 있으므로 컨트롤러 코드만 추가합니다.
<br><br>
- Close #62 
<br><br>
=> [Feat] 닉네임 수정과 프로필 소개 수정 API 추가 

src/database/database.providers.ts, src/search/search.module.ts, src/search/search.service.ts, src/signature/domain/signature.entity.ts, src/signature/domain/signature.page.entity.ts, src/signature/signature.module.ts, src/signature/signature.service.ts, src/user/user.service.ts
[Refactor] 시그니처, 탐색 이미지 업로드 및 가져오기 구현
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [Refactor] 시그니처, 탐색 이미지 업로드 및 가져오기 구현

src/signature/dto/detail-signature.dto.ts, src/signature/dto/page-signature.dto.ts, src/signature/dto/response-page-signature.dto.ts, src/signature/signature.service.ts
[Refactor] 시그니처 이미지 업로드 방식 수정 #73
<br><br>
기존 base64 인코딩 이미지 받기 -> blob 이미지 받기로 수정
<br><br>
<br><br>
- Close #73 
<br><br>
=> [Refactor] 시그니처 이미지 업로드 방식 수정 #73

src/diary/models/diary.image.entity.ts, src/journey/journey.controller.ts, src/journey/journey.service.ts, src/journey/model/journey.entity.ts, src/location/location.entity.ts, src/response/response.status.ts, src/schedule/schedule.entity.ts
지도에서 여정 불러오기 
<br><br>
여정 id 로 해당 여정의
title, startDate, endDate, 날짜별 location,날짜별  img 반환
<br><br>
/api/journey/:journeyId
<br><br>
- Close #이슈번호
<br><br>
=> [Feat] 홈 : 여정 불러오기 - 지도 API

src/diary/diary.controller.ts, src/diary/diary.service.ts, src/journey/journey.service.ts, src/response/response.status.ts
지도 - 여정 - 작성한 일지 확인하기
<br><br>
journeyId로 일지들 불러오기
-> 날짜, 일지 내용, 사진 
<br><br>
/api/v1/diary/get/:journeyId
<br><br>
- Close #이슈번호
<br><br>
=> [Feat] 홈 : 일지 불러오기 - 지도 API 

src/app.module.ts, src/diary/diary.controller.ts, src/diary/diary.service.ts, src/journey/journey.controller.ts, src/journey/journey.service.ts, src/journey/model/journey.entity.ts, src/map/map.controller.ts, src/map/map.module.ts, src/map/map.service.ts, src/map/month-info.dto.ts, src/schedule/schedule.entity.ts, src/schedule/schedule.service.ts
지도 API 들의 로직이 다 비슷해 ,함수 재사용성을 위해서 따로 Map 모듈로 분리했습니다.
=> [Refactor] 홈 : 지도 API 따로 분리 

src/main.ts
이미지 업로드를 위해 Max body size를 50MB로 상향한다.
<br><br>
<br><br>
<br><br>
- #24
<br><br>
=> [Chore] Max Body Size를 50MB로 상향

src/detail-schedule/detail-schedule.entity.ts, src/diary/diary.controller.ts, src/diary/diary.service.ts, src/diary/dtos/get-diary-img-url.dto.ts, src/diary/dtos/post-diary.dto.ts, src/diary/models/diary.entity.ts, src/diary/models/diary.image.entity.ts, src/journey/dtos/create-journey.dto.ts, src/journey/journey.controller.ts, src/journey/journey.service.ts, src/journey/model/journey.entity.ts, src/map/map.service.ts, src/response/response.status.ts, src/schedule/schedule.controller.ts, src/schedule/schedule.entity.ts
<br><br>
- 사용하지 않는 주석 및 Import문 삭제
- 월별 여정에 location 및 Img 정보 추가
- 여정 중복 생성 문제 해결
<br><br>
- Close #이슈번호
<br><br>
=> [Feat] 홈 : API

src/diary/diary.controller.ts, src/diary/diary.service.ts, src/diary/dtos/diary-info.dto.ts
일정 배너에서 '일지 확인하기' 
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [Feat] 홈 : 일지 불러오기 - 캘린더 API 

src/diary/diary.service.ts, src/diary/models/diary.image.entity.ts, src/journey/model/journey.entity.ts
=> [Bug] 홈 : 일지 수정하기 API 

src/member/member.controller.ts, src/member/member.service.ts, src/rule/dto/get-member-list.dto.ts, src/rule/rule.controller.ts, src/rule/rule.module.ts, src/rule/rule.service.ts
=> feat : 여행 규칙 조회 구현 완료

src/mate/dto/mate-recommend-profile.dto.ts, src/mate/dto/mate-with-common-location-response.dto.ts, src/mate/mate.service.ts
fix: 메이트 탐색 사용자 장소 기반 메이트 추천: 현재 로그인한 사용자 닉네임 추가
<br><br>
fix: 메이트 탐색 - 현재 로그인한 사용자 닉네임 추가
<br><br>
<br><br>
- Close #112
<br><br>
=> fix: 메이트 탐색 - 현재 로그인한 사용자 닉네임 추가 #112

src/journey/journey.service.ts, src/journey/model/journey.entity.ts, src/map/cursor-based-pagination-request.dto.ts.ts, src/map/map.controller.ts, src/map/map.service.ts, src/response/response.status.ts
<홈 화면 - 캘린더>
날짜 선택하면 일정 배너들 불러오기
<br><br>
커서기반 무한스크롤 구현 
cursorId? : 0(default),
pageSize? : 3(default)
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [Feat] 홈 : 월별 일정 불러오기 페이지네이션 

src/mate/dto/mate-profile-response.dto.ts, src/mate/mate.service.ts, src/user/user.service.ts
[Feat] 메이트 프로필 정보 팔로워, 팔로잉 수 추가 #128
<br><br>
<br><br>
<br><br>
- Close #128
<br><br>
=> [Feat] 메이트 프로필 정보 팔로워, 팔로잉 수 추가 #128

src/user/user.service.ts
=> fix : relations 수정

src/mate/dto/mate-profile-response.dto.ts, src/mate/mate.service.ts, src/signature/signature.service.ts
[Fix] 메이트 프로필 팔로우 여부 데이터 누락 수정 
<br><br>
<br><br>
<br><br>
- Close #143
<br><br>
=> [Fix/Refactor] 메이트 프로필 팔로우 여부 데이터 누락 해결 및 게시물 수 속성 추가

src/user/user.service.ts
일지를 정상적으로 불러오지 못하는 문제를 수정하라
<br><br>
<br><br>
일지를 가져오기 위해서는 아래 종속 관계를 따라야 한다.
> user -> journey -> schedules -> diary -> diaryImage
<br><br>
- Close #147
<br><br>
=> [Fix] 일지를 정상적으로 불러오지 못하는 문제를 수정하라

src/user/user.service.ts
일지 리스트 응답값을 수정하라
<br><br>
<br><br>
<br><br>
- Close #147
<br><br>
=> [Update] 일지 리스트 응답값을 수정하라

src/rule/rule.service.ts, src/user/user.service.ts
=> fix : 초대할 여행 멤버 검색 에러 해결

src/rule/rule.service.ts
fix: 여행 규칙 댓글 정렬 순서 변경
<br><br>
fix: 여행 규칙 댓글 정렬 순서 변경
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> fix: 여행 규칙 댓글 정렬 순서 변경

src/rule/dto/get-search-member-at-create.dto.ts, src/rule/rule.controller.ts, src/rule/rule.service.ts
case1. 여행 규칙 생성
case2. 여행 규칙 수정
=> feat : 초대할 멤버 검색 케이스 분리

src/signature/signature.service.ts, src/user/user.service.ts
[BugFix] 시그니처 수정하기 이미지 예외처리 구현하기 #192
<br><br>
<br><br>
signature.service.ts
<br><br>
- Close #이슈번호
<br><br>
=> [BugFix] 시그니처 수정하기 이미지 예외처리 구현하기 #192

src/signature/dto/comment/get-signature-comment.dto.ts, src/signature/signature.comment.controller.ts, src/signature/signature.comment.service.ts
[Feat] 시그니처 댓/답글 수정하기 api 개발
<br><br>
- [Feat] 시그니처 댓/답글 수정하기 api 개발
- 댓글 날짜 데이터 타입 변경
<br><br>
<br><br>
- #180
<br><br>
=> [Feat] 시그니처 댓/답글 수정하기 api 개발 #180

src/rule/rule.service.ts
=> fix : 여행 규칙 수정 과정에서 멤버 검증 추가

src/rule/dto/update-rule.dto.ts, src/rule/rule.controller.ts, src/rule/rule.service.ts
여행 규칙 수정 후, 여행 규칙 확인하기 페이지에서 발생한 에러 해결
=> fix : sort 에러 해결

src/signature/signature.comment.controller.ts, src/signature/signature.comment.service.ts
[Feat] 시그니처 댓글 삭제하기 구현 
<br><br>
<br><br>
<br><br>
- Close #180 
<br><br>
=> [Feat] 시그니처 댓글 삭제하기 구현 

src/signature/dto/comment/get-signature-comment.dto.ts, src/signature/signature.comment.service.ts
Refactor: 시그니처 댓글 삭제 권한 변경 #207
<br><br>
<br><br>
<br><br>
- Close #207 
<br><br>
=> Refactor: 시그니처 댓글 삭제 권한 변경 #207

src/rule/rule.controller.ts, src/rule/rule.service.ts
[초대할 멤버 검색 결과]
- 본인은 안뜨도록
- 팔로우하는 유저들만 검색 결과로 나오도록
[소셜 계정 사용자 규칙 상세 페이지 조회 안되는 에러]
- subRule 검색 조건 수정 (id가 null값으로 전송돼서 에러 발생)
=> fix : 소셜 계정 사용자 규칙 상세 페이지 조회 안되는 에러

src/rule/rule.service.ts
본인이 팔로우하는 사용자만 검색 결과에 뜨도록 검색 조건 설정하면서, 본인은 자동으로 안 뜸 -> 본인 안나오도록 설정하는 검색 조건 삭제
=> fix : 초대할 멤버 검색 조건 수정

src/rule/rule.service.ts
[규칙에 초대할 멤버 검색]
: UserEntity의 find 조건을, 검색 결과로 나와야하는 사용자를 대상으로
[여행 규칙 상세 조회]
: id에 null값이 담겨가는 에러 (relations 사용 과정에서 발생)
=> fix : 검색 결과 에러, 여행 규칙 상세 조회 에러

src/follow/follow.service.ts, src/mate/cursor-page/cursor-page-option.dto.ts, src/rule/dto/cursor-page.options.dto.ts, src/rule/dto/get-search-member-at-create.dto.ts, src/rule/rule.service.ts
[규칙에 초대할 멤버 검색 결과]
: readonly, import 오류
: where 조건 id 중복 사용 불가 -> cursorId 적용하는 부분 분리 후, filter, slice 이용
=> fix : 규칙에 초대할 멤버 검색 에러 해결

src/follow/follow.service.ts, src/rule/rule.service.ts
: 여행 규칙 최초 작성 시 규칙 멤버 검색과 동일한 원인
[팔로우팔로워 목록]
+ 본인도 검색 결과에 포함되도록
[규칙 수정에서 멤버 검색 결과]
+ 이미 규칙에 참여하는지 여부 isInvited
=> fix : 팔로우팔로워 목록, 규칙 멤버 수정에서 검색 결과 에러 해결

src/follow/follow.service.ts, src/rule/rule.service.ts
=> fix : 탈퇴한 회원은 검색 결과에서 제외

src/user/user.service.ts
[메이트탐색 : 팔로우, 팔로잉 리스트]
: 탈퇴한 회원 제외
=> fix : 팔로우리스트 탈퇴한 회원 제외

src/mate/mate.service.ts, src/search/search.service.ts, src/signature/domain/signature.entity.ts, src/signature/domain/signature.like.entity.ts, src/signature/signature.service.ts, src/user/user.service.ts
Refactor: 탈퇴한 사용자 필터링 추가
<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [Refactor] 탈퇴한 사용자 필터링 추가 #230

src/search/search.service.ts, src/signature/domain/signature.page.entity.ts, src/signature/signature.service.ts
fix: 탐색 - 시그니처 썸네일 가져오기 버그 해결
<br><br>
시그니처 이미지 에러에 대한 예외처리 구성
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> fix: 탐색 - 시그니처 썸네일 가져오기 버그 해결

src/search/search.service.ts
[hotfix] 최신 시그니처 중복 push 오류 해결
<br><br>
[hotfix] 최신 시그니처 중복 push 오류 해결
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [hotfix] 최신 시그니처 중복 push 오류 해결

src/signature/signature.service.ts
refactor: 홈 시그니처 최신순으로 반환하기
<br><br>
refactor: 홈 시그니처 최신순으로 반환하기
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [Refactor] 홈 시그니처 최신순으로 반환하기

src/search/search.service.ts
[Refactor] 메이트 탐색 검색 결과 최신순 정렬
<br><br>
[Refactor] 메이트 탐색 검색 결과 최신순 정렬
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [Refactor] 메이트 탐색 검색 결과 최신순 정렬

src/follow/follow.service.ts
[BugFix] 팔로워 목록에서 isFollow = true 버그 픽스
<br><br>
[BugFix] 팔로워 목록에서 isFollow = true 버그 픽스
<br><br>
<br><br>
- Close #이슈번호
<br><br>
=> [BugFix] 팔로워 목록에서 isFollow = true 버그 픽스

src/comment/domain/comment.entity.ts
=> fix : 댓글 글자 수 변경

src/rule/domain/rule.main.entity.ts, src/rule/domain/rule.sub.entity.ts
규칙 전체 제목, 개별 제목 글자 수 제한 수정 (200자)
=> fix : 규칙 제목 글자 수 제한 수정
